set(LLVM_ENABLE_PROJECTS "clang")
set(LLVM_TARGETS_TO_BUILD "X86")

# Disable all executables/tools
set(LLVM_INCLUDE_TOOLS OFF)
set(LLVM_INCLUDE_TESTS OFF)
set(LLVM_INCLUDE_EXAMPLES OFF)
set(LLVM_INCLUDE_DOCS OFF)
set(LLVM_INCLUDE_UTILS OFF)
set(LLVM_INCLUDE_BENCHMARKS OFF)
set(LLVM_INCLUDE_DEBUGINFO OFF)

# Minimal runtime
set(LLVM_ENABLE_RTTI OFF)
set(LLVM_ENABLE_EH OFF)
set(LLVM_ENABLE_THREADS OFF)
set(LLVM_BUILD_STATIC_LIBS ON)
set(LLVM_LINK_LLVM_DYLIB OFF)
set(LLVM_ENABLE_BINDINGS OFF)
set(LLVM_ENABLE_WARNINGS OFF)
set(LLVM_ENABLE_ASSERTIONS OFF)
set(LLVM_ENABLE_ORC OFF)

# Minimal clang
set(CLANG_ENABLE_STATIC_ANALYZER OFF)
set(CLANG_INCLUDE_DOCS OFF)
set(CLANG_INCLUDE_TESTS OFF)
set(CLANG_INCLUDE_TOOLS OFF)
set(CLANG_INCLUDE_EXAMPLES OFF)

# enable static
set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)
set(CMAKE_POSITION_INDEPENDENT_CODE OFF)

add_subdirectory(libs/llvm/llvm llvm-build)

# Minimal LLVM components for compiling C++ code
set(LLVM_COMPONENTS
  Core
  Support
  IRReader
  Target
  MC
  X86Info
  X86Desc
  X86CodeGen
  Option
)

llvm_map_components_to_libnames(LLVM_LIBS ${LLVM_COMPONENTS})