# set(SDLIMAGE_PNG OFF CACHE BOOL "Disable PNG support" FORCE)
# set(SDLIMAGE_JPG OFF CACHE BOOL "Disable JPG support" FORCE)
# do I look like I know what a jpeg is, I'm just trying to print out a picture of a god dang hot dog.
set(SDLIMAGE_TIF OFF CACHE BOOL "Disable TIFF support" FORCE)
set(SDLIMAGE_WEBP OFF CACHE BOOL "Disable WebP support" FORCE)
set(SDLIMAGE_AVIF OFF CACHE BOOL "Disable AVIF support" FORCE)
set(SDLIMAGE_JXL OFF CACHE BOOL "Disable JXL support" FORCE)
set(SDLIMAGE_QOI OFF CACHE BOOL "Disable QOI support" FORCE)
set(SDLIMAGE_GIF OFF CACHE BOOL "Disable GIF support" FORCE)
set(SDLIMAGE_BMP OFF CACHE BOOL "Disable BMP support" FORCE)
set(SDLIMAGE_XPM OFF CACHE BOOL "Disable XPM support" FORCE)
set(SDLIMAGE_XCF OFF CACHE BOOL "Disable XCF support" FORCE)
set(SDLIMAGE_LBM OFF CACHE BOOL "Disable LBM support" FORCE)
set(SDLIMAGE_PCX OFF CACHE BOOL "Disable PCX support" FORCE)
set(SDLIMAGE_PNM OFF CACHE BOOL "Disable PNM support" FORCE)
set(SDLIMAGE_SVG OFF CACHE BOOL "Disable SVG support" FORCE)
set(SDLIMAGE_TGA OFF CACHE BOOL "Disable TGA support" FORCE)
set(SDLIMAGE_MOD OFF CACHE BOOL "Disable MOD support" FORCE)
set(SDLIMAGE_OPUS OFF CACHE BOOL "Disable OPUS support" FORCE)

set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)

add_subdirectory("${CMAKE_SOURCE_DIR}/libs/sdl_image" SDL_image_BUILD)

if(TARGET SDL3_image)
    add_library(SDL3_image::SDL3_image ALIAS SDL3_image)
    target_compile_options(SDL3_image PRIVATE -Wno-unused-parameter)
elseif(TARGET SDL3_image-static)
    add_library(SDL3_image::SDL3_image ALIAS SDL3_image-static)
    target_compile_options(SDL3_image-static PRIVATE -Wno-unused-parameter)
endif()