# #flags
# set(SLANG_ENABLE_SLANG_RHI ON)
# set(BUILD_SHARED_LIBS OFF)
# set(BUILD_STATIC_LIBS ON)
# set(SLANG_USE_SYSTEM_MINIZ OFF)
# set(SLANG_USE_SYSTEM_LZ4 OFF)
# set(SLANG_USE_SYSTEM_GLSLANG OFF)
# set(SLANG_LIB_TYPE STATIC)

# set(SLANG_ENABLE_CUDA OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_OPTIX OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_NVAPI OFF CACHE BOOL "" FORCE)

# set(SLANG_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_FIDDLE OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_SLANGC OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_SLANGD OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_SLANGRT OFF CACHE BOOL "" FORCE)

# set(SLANG_ENABLE_GFX OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_PREBUILT_BINARIES OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_RELEASE_LTO OFF CACHE BOOL "" FORCE)
# set(SLANG_SLANG_LLVM_FLAVOR DISABLE CACHE STRING "" FORCE)

# set(SLANG_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
# set(SLANG_ENABLE_REPLAYER OFF CACHE BOOL "" FORCE)

# add_subdirectory("${CMAKE_SOURCE_DIR}/libs/slang")

# #make it an alias
# add_library(SLANG::SLANG ALIAS slang)