include(FetchContent)

set(BUILD_SHARED_LIBS ON)
set(BUILD_STATIC_LIBS OFF)

set(SPDLOG_BUILD_SHARED OFF)
set(SPDLOG_BUILD_TESTS OFF)
set(SPDLOG_BUILD_EXAMPLE OFF)
set(SPDLOG_BUILD_BENCH OFF)
set(SPDLOG_BUILD_ALL OFF)
set(SPDLOG_INSTALL OFF)
set(SPDLOG_FMT_EXTERNAL OFF)
set(SPDLOG_FMT_EXTERNAL_HO OFF)
set(SPDLOG_USE_STD_FORMAT OFF)
set(SPDLOG_NO_EXCEPTIONS ON)
set(SPDLOG_NO_THREAD_ID ON)
set(SPDLOG_NO_TLS ON)
set(SPDLOG_NO_ATOMIC_LEVELS ON)
set(SPDLOG_DISABLE_DEFAULT_LOGGER ON)
set(SPDLOG_FWRITE_UNLOCKED ON)
set(SPDLOG_SYSTEM_INCLUDES ON)
set(SPDLOG_ENABLE_PCH OFF)
set(SPDLOG_BUILD_PIC OFF)

FetchContent_Declare(
	spdlog
	GIT_REPOSITORY https://github.com/gabime/spdlog.git
	GIT_TAG v1.17.0
)
FetchContent_MakeAvailable(spdlog)