option(YAML_CPP_BUILD_TOOLS OFF)
set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)
cmake_policy(PUSH)
cmake_policy(VERSION 3.15)
add_subdirectory("${CMAKE_SOURCE_DIR}/libs/yaml-cpp" YAML_build)
cmake_policy(POP)
add_library(yaml-cpp::yaml-cpp ALIAS yaml-cpp)
target_compile_options(yaml-cpp INTERFACE -w)