name: example1
id: com.ryan.example1
version: 0.0.1

# incompatible_modules: # if two mods are incompatible list the ids below
#   - id: com.ryan.example1
# requires:
#   - id: com.ryan.example1
#     compatible_range: 0.0.0-0.0.1 #inclusive

include:
  BigObjects: false
  Rendering: true
  SDL3: false