name: game
id: com.ryan.game
version: 0.0.1

# requires:
#   - id: com.ryan.game

script_path: scripts/hello.wasm

folder_passthrough:
  - path: assets
    type: ro #ro/rw - read only vs read write
  # - name: saves
  #   type: rw

permissions: 
  include_rendering: true
  include_bigvars: true
  include_objects: true
  include_glm: true