name: example
id: com.ryan.example
version: 0.0.1

# incompatible_modules: # if two mods are incompatible list the ids below
#   - id: com.ryan.example
# requires:
#   - id: com.ryan.example
#     compatible_range: 0.0.0-0.0.1 #inclusive

include:
  objects: true
  rendering: true